<?php
/**
* Implementation of hook_menu().
*/
function bcmlib_periodicals_menu() {
/*
	$items['periodicals'] = array(
	      'title' => 'Import EG items',
	      'type'=> MENU_LOCAL_TASK,
	      'page callback' => '_periodicals_page_callback',
	      'page arguments' => array('bcmlib_periodicals_acquisition_admin'),
	      'access arguments' => array('access content'),
	      '#required' => TRUE,
	      'weight' => 1,
	    );
*/
	$items['periodicals/%'] = array(
	      'title' => 'Periodicals',
	      'type'=> MENU_CALLBACK,
	      'page callback' => '_periodicals_page_callback',
	      'page arguments' => array(1),
	      'access arguments' => array('access content'),
	      '#required' => TRUE,
	      'weight' => 1,
	    );
	return $items;
}
function _periodicals_page_callback($arg1){

	_mobile_warning();

	drupal_set_title('');

	return '<div class="more-link" style="margin-bottom:24px;"><a href="/browse/periodicals">Back to Periodical List</a></div><div id="periodical-content" style="margin:0; padding:0; background:none; border:none; display:block; width:100%;"></div><script type="text/javascript">jQuery("#periodical-content").load("/_periodicals/html/'.$arg1.'");</script><div class="more-link" style="margin-bottom:24px;"><a href="/browse/periodicals">Back to Periodical List</a></div>';
}
function _mobile_warning(){
	// Journals & Magazines List (Local Holdings) page
	//if(isset($build['#node']) && $build['#node']->nid == 79571){
		$detect = new Mobile_Detect;
		if($detect->isMobile()){
			 drupal_set_message(t('Please be aware that the content of this page is not properly formatted for mobile viewing.'), 'warning');
		}
	//}
}